In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.23.1


In [3]:
data_1 = [5, 9, 2.5, 3, 1]
array_1 = np.array(data_1)

In [5]:
print(array_1)

[5.  9.  2.5 3.  1. ]


In [6]:
data_2 = [[1, 3, 5, 7, 9], [2, 4, 6, 8, 10]]
array_2 = np.array(data_2)

In [7]:
print(array_2)

[[ 1  3  5  7  9]
 [ 2  4  6  8 10]]


In [8]:
print(array_2.ndim)
print(array_2.shape)

2
(2, 5)


In [9]:
print(array_1.dtype)
print(array_2.dtype)

float64
int32


In [10]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.zeros((5, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [12]:
np.ones((2, 3, 8))

array([[[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]]])

In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(5, 30, 3)  # 시작 값, 종료 값, 단계 지정

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29])

In [5]:
array_1 = np.array([1, 3, 5, 7, 9], dtype=np.float32)
array_2 = np.array([1, 3, 5, 7, 9], dtype=np.int16)

In [6]:
array_1.dtype

dtype('float32')

In [7]:
array_2.dtype

dtype('int16')

In [8]:
array_2_float = array_2.astype(np.float64)
array_2_float.dtype

dtype('float64')

In [9]:
num_strings = np.array(['-3.15', '5', '8.4', '21', '-12'], dtype=np.string_)
num_strings.dtype

dtype('S5')

In [10]:
num_strings = num_strings.astype(float)   # float 대신 np.float64 입력 가능
num_strings

array([ -3.15,   5.  ,   8.4 ,  21.  , -12.  ])

In [7]:
num_strings.dtype

dtype('float64')

In [21]:
array_1 = np.array([[1., 2., 3., 4., 5.], [6., 7., 8., 9., 10.]])
array_2 = np.array([[1., 3., 5., 7., 9.], [2., 4., 6., 8., 10.]])

In [23]:
array_1 * array_2

array([[  1.,   6.,  15.,  28.,  45.],
       [ 12.,  28.,  48.,  72., 100.]])

In [24]:
array_1 - array_2

array([[ 0., -1., -2., -3., -4.],
       [ 4.,  3.,  2.,  1.,  0.]])

In [25]:
1 / array_1

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ]])

In [27]:
array_2 ** 0.25

array([[1.        , 1.31607401, 1.49534878, 1.62657656, 1.73205081],
       [1.18920712, 1.41421356, 1.56508458, 1.68179283, 1.77827941]])

In [28]:
array_1 > array_2

array([[False, False, False, False, False],
       [ True,  True,  True,  True, False]])

In [24]:
array_1d = np.arange(15)
array_1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [25]:
array_1d[7]

7

In [26]:
array_1d[[7, 9]]

array([7, 9])

In [27]:
array_1d[4:7]

array([4, 5, 6])

In [28]:
array_1d[4:7] = 10
array_1d

array([ 0,  1,  2,  3, 10, 10, 10,  7,  8,  9, 10, 11, 12, 13, 14])

In [11]:
array_2d = np.array([[2, 4, 6], [3, 6, 9], [4, 8, 12]])
array_2d

array([[ 2,  4,  6],
       [ 3,  6,  9],
       [ 4,  8, 12]])

In [13]:
array_2d[1]

array([3, 6, 9])

In [15]:
array_2d[1][2]   # array_2d[1, 2] 형식으로 써도 됨

9

In [32]:
array_2d[:2]

array([[2, 4, 6],
       [3, 6, 9]])

In [35]:
array_2d[:2, :2]

array([[2, 4],
       [3, 6]])

In [41]:
array_2d[[0, 1], :2]

array([[2, 4],
       [3, 6]])

In [44]:
array_2d[:, :1]

array([[2],
       [3],
       [4]])

In [84]:
np.random.seed(1000)

In [85]:
np.random.rand(5)

array([0.65358959, 0.11500694, 0.95028286, 0.4821914 , 0.87247454])

In [86]:
np.random.rand(10)

array([0.21233268, 0.04070962, 0.39719446, 0.2331322 , 0.84174072,
       0.20708234, 0.74246953, 0.39215413, 0.18225652, 0.74353941])

In [87]:
np.random.randn(10)

array([-0.4122031 , -0.07400906, -0.92893693,  1.39006147,  1.19506933,
        0.70734239,  0.99296211,  0.13946394, -0.08988248, -0.14974264])

In [88]:
np.random.randn(5, 3)

array([[ 0.4055338 , -0.75133127,  0.93131848],
       [-0.24745023, -0.27072883, -1.27939856],
       [-1.07900875, -0.08796666,  2.05225999],
       [-1.23931612,  1.10970741, -1.15768513],
       [ 0.09870641, -1.4651006 , -1.75193341]])

In [89]:
np.random.randint(10, size=15)

array([9, 6, 2, 9, 5, 8, 5, 6, 9, 6, 7, 6, 3, 4, 8])

In [90]:
np.random.randint(5, 25, size=10)

array([ 6,  8, 18, 18, 18, 12, 23,  5,  9, 19])

In [92]:
np.random.randint(5, 25, size=(3, 8))

array([[ 8,  5, 17, 17, 17, 23, 22, 21],
       [20, 13, 14,  6, 22, 19, 18,  5],
       [ 7,  7,  6, 15, 13,  7, 19, 21]])

In [76]:
np.random.normal(size=(5, 3))

array([[ 0.66728131, -0.80611561, -1.19606983],
       [-0.40596016, -0.18237734,  0.10319289],
       [-0.13842199,  0.70569237,  1.27179528],
       [-0.98674733, -0.33483545, -0.0994817 ],
       [ 0.4071921 ,  0.91938754,  0.31211801]])

In [78]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
np.random.shuffle(data)

In [80]:
data

array([8, 3, 4, 9, 2, 5, 6, 7, 0, 1])

In [93]:
np.random.choice(10, 5, replace=False)

array([6, 0, 2, 7, 4])

In [105]:
np.random.choice(10, 5, replace=True)

array([9, 5, 6, 3, 9])

In [110]:
np.random.choice(3, 12, p=[0.3, 0.7, 0])

array([1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1])

In [108]:
np.random.choice(['apple', 'banana', 'orange'], 8)

array(['apple', 'apple', 'apple', 'banana', 'orange', 'apple', 'banana',
       'banana'], dtype='<U6')

In [24]:
array = np.random.randint(30, size=20)
array

array([17, 21,  8, 13, 22, 16,  0,  7, 26, 22, 12, 24, 13, 12, 27, 24,  1,
       23, 15, 21])

In [25]:
len(array)

20

In [27]:
np.mean(array)

16.2

In [35]:
array.mean()

16.2

In [36]:
np.median(array)

16.5

In [30]:
np.std(array)

7.73692445355388

In [31]:
np.var(array)

59.86

In [39]:
np.min(array)

0

In [38]:
np.max(array)

27

In [28]:
array.sum()

324

In [37]:
array.cumsum()

array([ 17,  38,  46,  59,  81,  97,  97, 104, 130, 152, 164, 188, 201,
       213, 240, 264, 265, 288, 303, 324], dtype=int32)

In [40]:
array.cumprod()

array([      17,      357,     2856,    37128,   816816, 13069056,
              0,        0,        0,        0,        0,        0,
              0,        0,        0,        0,        0,        0,
              0,        0], dtype=int32)

In [56]:
np.percentile(array, 0)

-2.5498510958117944

In [57]:
np.percentile(array, 25)

-0.728832481992645

In [59]:
np.percentile(array, 50)

-0.24013222393447692

In [60]:
np.percentile(array, 75)

0.519114636929271

In [61]:
np.percentile(array, 100)

2.1764809671933074

In [48]:
array = np.random.randn(50)

In [51]:
(array > 0).sum()

19

In [55]:
bools = np.array([1, 1, 0, 0])
bools

array([1, 1, 0, 0])

In [53]:
bools.any()

True

In [54]:
bools.all()

False

In [64]:
array = np.random.randint(20, size=10)
array

array([16,  8,  1,  9, 13,  8,  4,  2,  2,  2])

In [65]:
array.sort()

In [66]:
array

array([ 1,  2,  2,  2,  4,  8,  8,  9, 13, 16])

In [9]:
fruits = np.array(['apple', 'banana', 'kiwi', 'apple', 'kiwi', 'lemon', 'banana', 'lemon'])
fruits

array(['apple', 'banana', 'kiwi', 'apple', 'kiwi', 'lemon', 'banana',
       'lemon'], dtype='<U6')

In [7]:
np.unique(fruits)

array(['apple', 'banana', 'kiwi', 'lemon'], dtype='<U6')

In [8]:
sorted(set(fruits))

['apple', 'banana', 'kiwi', 'lemon']

In [12]:
numbers = np.array([5 ,7, 1, 2, 1, 7, 8, 5])
numbers

array([5, 7, 1, 2, 1, 7, 8, 5])

In [13]:
np.unique(numbers)

array([1, 2, 5, 7, 8])

In [14]:
numbers_2 = np.array([1, 4, 6, 9, 2, 3, 5, 1])
numbers_2

array([1, 4, 6, 9, 2, 3, 5, 1])

In [15]:
np.intersect1d(numbers, numbers_2)

array([1, 2, 5])