In [1]:
import pandas as pd

In [2]:
print(pd.__version__)

1.4.3


In [2]:
ser = pd.Series([1 ,3, 5, 7, 9])
ser

0    1
1    3
2    5
3    7
4    9
dtype: int64

In [4]:
ser.index

RangeIndex(start=0, stop=5, step=1)

In [3]:
ser.values

array([1, 3, 5, 7, 9], dtype=int64)

In [21]:
data = np.random.randint(0, 10, 5)
index = ['a', 'b', 'c', 'd', 'e']
series = pd.Series(data=data,
                  index=index,
                  name='series_from_ndarray')
print(series)

a    7
b    4
c    2
d    8
e    4
Name: series_from_ndarray, dtype: int32


In [18]:
data = {'서울': 70000, '부산': 52000, '대전': 35000, '광주': 40000, '제주도': 28000}
series = pd.Series(data=data, name='series_from_dict')
print(series)

서울     70000
부산     52000
대전     35000
광주     40000
제주도    28000
Name: series_from_dict, dtype: int64


In [19]:
city = ['광주', '대전', '부산', '서울', '울릉도']
series = pd.Series(data=data, index=city, name='series_from_dict')
print(series)

광주     40000.0
대전     35000.0
부산     52000.0
서울     70000.0
울릉도        NaN
Name: series_from_dict, dtype: float64


In [9]:
series.name

'series_from_dict'

In [10]:
series.values

array([40000., 35000., 52000., 70000.,    nan])

In [32]:
series_tolist = series.tolist()

In [33]:
type(series_tolist)

list

In [36]:
data = {'도시' : ['서울', '서울', '서울', '부산', '부산', '부산'],
        '연도' : [2020, 2019, 2018, 2020, 2019, 2018],
        '인구수' : [15865, 15964, 16034, 4342, 4380, 4416]}

frame = pd.DataFrame(data)

In [28]:
frame

도시    연도    인구수
0  서울  2020  15865
1  서울  2019  15964
2  서울  2018  16034
3  부산  2020   4342
4  부산  2019   4380
5  부산  2018   4416

In [34]:
frame = pd.DataFrame(data, columns=['연도', '도시', '인구수'])
frame

연도  도시    인구수
0  2020  서울  15865
1  2019  서울  15964
2  2018  서울  16034
3  2020  부산   4342
4  2019  부산   4380
5  2018  부산   4416

In [35]:
frame = pd.DataFrame(data, columns=['연도', '도시', '인구수', '변화율'])
frame

연도  도시    인구수  변화율
0  2020  서울  15865  NaN
1  2019  서울  15964  NaN
2  2018  서울  16034  NaN
3  2020  부산   4342  NaN
4  2019  부산   4380  NaN
5  2018  부산   4416  NaN

In [12]:
data = {'컬럼1' : pd.Series(data=np.random.randint(10, 100, 5),
                                  index=['가', '나', '다', '라', '마']),
        '컬럼2' : pd.Series(data=np.random.randint(10, 100, 5),
                                  index=['가', '나', '다', '라', '마']),
        '컬럼3' : pd.Series(data=np.random.randint(10, 100, 5),
                                  index=['가', '나', '다', '라', '마'])}
frame = pd.DataFrame(data=data)

In [13]:
frame

컬럼1  컬럼2  컬럼3
가   61   82   84
나   63   69   10
다   43   78   10
라   90   95   69
마   30   14   66

In [15]:
frame.values

array([[61, 82, 84],
       [63, 69, 10],
       [43, 78, 10],
       [90, 95, 69],
       [30, 14, 66]])